### ISSUE TITLE
Modificações que devem ser feita no Front-End

### ISSUE THREAD

**Issue by EuCarlos** [Mural-de-Vagas-de-Estagios-FATEC/fatec-back-end#1]
Algumas alterações que devem ter um alerta

### 1. home.php
- [ ] A div com o id `pagination-container` não está sendo exibida, não sei o PHP interfere nisso, ou então se o jquery não está sendo importado de forma correta.
- [ ] No `<footer>` acrescentar as referencias nos ícones das mídias sociais:
```
<a href="https://www.instagram.com/fatecitaquaquecetuba/"><i class="fab fa-instagram"></i></a>
<a href="https://www.linkedin.com/company/fatec-itaquaquecetuba/"><i class="fab fa-linkedin"></i></a>
<a href="https://www.youtube.com/channel/UC6LUrLB2BOaw_J_LOHyaisA"><i class="fa fa-youtube"></i></a>
<a href="https://twitter.com/FatecItaqua"><i class="fa fa-twitter"></i></a>
```

### 2. forum.php
- [ ] Remover "**, Lorem Ipsum is simply dummy!**" do `<p class="texto-perfil-hidden">Olá Pedro Henrique, Lorem Ipsum is simply dummy!</p>`ou ser substituido por ", seja bem-vindo!" (**essa classe fica escondida, ela só aparece quando diminui o tamanho da janela do navegador**)

### 3. lado_esquerdo.php
- [ ] Mudar ou remover também no `lado_esquerdo.php` o texto de preenchimento
```
<!-- QUANTIDADE DE VAGAS -->
<div class="texto-perfil">
	Olá <?= $_SESSION['nome']; ?>, seja bem-vindo!<br><br>
</div>
```

**Comment by EuCarlos** [comment]
Algumas alterações que devem ter um alerta

### 4. estagio_obrigatorio.php
- [ ] remover texto "**What is Lorem Ipsum?**"

### 5. recuperar_senha.php
- [ ] No `<footer>` acrescentar as referencias nos ícones das mídias sociais

### 6. cadastros.html
- [ ] Substituir Ex-aluno por Egresso no botão de escolha no cadastro.
- [ ] No `<footer>` acrescentar as referencias nos ícones das mídias sociais

### 7. index.php
- [ ] No `<footer>` acrescentar as referencias nos ícones das mídias sociais
- [ ] Em "**Vagas de estágio para alunos da Fatec Itaquá**", remover o testo de preenchimento e substituir por:
```
Na plataforma, como função principal é possível usar um mural de vagas para estágios onde permite que qualquer usuário possa visualizar as vagas com seus dados e requisitos assim permitindo aos alunos que identifiquem vagas com os seus perfis e melhor divulgação das vagas.
```
- [ ] Em "**Divulgue vagas da sua empresa em nossa plataforma**", remover o testo de preenchimento e substituir por:
```
Para empresas  interessadas em anunciar vagas temos a área de solicitação de cadastro de vaga , é recomendado que a empresa faça o cadastro da conta e entre na página de solicitação de divulgação de vagas para que elas possam aparecer no mural de vagas, é possível também solicitar para a instituição de ensino através de telefone e a própria instituição cadastrará a vaga.
```
- [ ] Em "**Network entre alunos e ex-alunos da Fatec Itaquá**", remover o testo de preenchimento e substituir por:
```
Para uma melhor interação e compartilhamento de experiencias entre alunos interessados em estágios e os egressos, existe o fórum que permite que a comunicação seja publica e proporciona que pessoas com experiencia na área possam dar conselhos ou apresentar novas oportunidade de crescimento na área
```

**Comment by PedroHCavalcanti** [comment]
Feito
